version: '3'
services:
  gekko:
    restart: always
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./config-docker.js:/usr/src/app/config.js # let's put our configuration into custom file "config-docker.js"
    depends_on:
      - postgresql
    environment:
     - HOST
     - PORT
     - USE_SSL
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}:${PORT}"
  postgresql:
    restart: always # no | on-failure | unless-stopped
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: gekko
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
