takeProfit = 1.2 # 20%
#stopLoss = 0.99 # 1%
#USE_MARKET_LOST_FOR_TREND = true
#EXIT_ON_AAAT_CHANGE = true # treat as Stop Loss

[aaat]
USE_HEIKEN = false
sellOnRedThresholdMedium = true
sellOnRedThresholdHigh = true

[margin]
useShort = true

isPersistent = false

# good strategy for big swings, performs badly on sideways market
# run with pair USDT/BTC, candle 1hr, Warmup 280
# 2.5 yrs - 150%, '18 1yr - -23%
# lot of trades, will exit if enter bearland (no zasazhenniy)
# if traded with no fees (e.g. on some exchanges) it gives 70%-100% times more (2.5yrs-250%)!
# for pairs btc/eth and btc/ltc ->
# takeProfit = 1.05
# will give ~30-40% / yr
