ATR_Period = 14

[thresholds]
ATR_LOW_SELL = 32
ATR_HIGH_BUY = 20
RSI_HIGH_SELL = 70
RSI_LOW_BUY = 30
RSI_HIGH_SELL_ALWAYS = 75
RSI_LOW_BUY_ALWAYS = 15
STOP_LOSS_RATIO = 0.97
STOP_LOSS_TIMEOUT  = 60
TIMEOUT_EXIT_MINUTES = 18000
TIMEOUT_EXIT_COEF = 1.01
