ATR_Period = 14

[thresholds]
ATR_LOW_SELL = 0.000032
ATR_HIGH_BUY = 0.000036
RSI_HIGH_SELL = 70
RSI_LOW_BUY = 30
RSI_LOW_BUY_ALWAYS = 20
RSI_HIGH_SELL_ALWAYS = 75
STOP_LOSS_RATIO = 0.99
TIMEOUT_EXIT_MINUTES = 60
TIMEOUT_EXIT_COEF = 1.006
TIMEOUT_EXIT_MINUTES_2 = 90
TIMEOUT_EXIT_COEF_2 = 0.99
TIMEOUT_EXIT_MINUTES_3 = 120
TIMEOUT_EXIT_COEF_3 = 0.98
