ATR_Period = 14

[thresholds]
ATR_LOW_SELL = 0.1
ATR_HIGH_BUY = 0.3
RSI_HIGH_SELL = 70
RSI_LOW_BUY = 30
RSI_LOW_BUY_ALWAYS = 20
RSI_HIGH_SELL_ALWAYS = 80
STOP_LOSS_RATIO = 0.996
TIMEOUT_EXIT_MINUTES = 60
TIMEOUT_EXIT_COEF = 1.005
TIMEOUT_EXIT_MINUTES_2 = 120
TIMEOUT_EXIT_COEF_2 = 0.996
TIMEOUT_EXIT_MINUTES_3 = 150
TIMEOUT_EXIT_COEF_3 = 0.9
