takeProfit = 1.01 # 1%
stopLoss = 0.99 # 1%
USE_MARKET_LOST_FOR_TREND = true
EXIT_ON_AAAT_CHANGE = true # treat as Stop Loss

[aaat]
USE_HEIKEN = false
lengthMultiplyer = 24

#not used yet:

[rsi]
interval = 1
low = 29
high = 79
persistence = 1

# indicators = ["Bollinger Bands"]

[bbands]
TimePeriod = 20
NbDevUp = 3
NbDevDn = 3
# abount:
# start with 1hr && 24 hr (LM = 24)
